<a href="https://colab.research.google.com/github/Aishika3/Image_Classification_CNN/blob/main/Quantum_Circuit_Example_and_Stimulator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

# Dummy placeholder for quantum_circuit (replace with real implementation)
class quantum_circuit:
    def __init__(self, num_qubits, state_vector=None):
        self.n = num_qubits
        self.dim = 2 ** self.n
        self.state_vector = state_vector if state_vector is not None else torch.ones(self.dim, dtype=torch.cfloat)
        self.I = torch.eye(2, dtype=torch.cfloat)
        self.x_matrix = torch.tensor([[0, 1], [1, 0]], dtype=torch.cfloat)
        self.y_matrix = torch.tensor([[0, -1j], [1j, 0]], dtype=torch.cfloat)
        self.z_matrix = torch.tensor([[1, 0], [0, -1]], dtype=torch.cfloat)
        self.h_matrix = 1 / torch.sqrt(torch.tensor(2.0)) * torch.tensor([[1, 1], [1, -1]], dtype=torch.cfloat)
        self.proj_0 = torch.tensor([[1, 0], [0, 0]], dtype=torch.cfloat)
        self.proj_1 = torch.tensor([[0, 0], [0, 1]], dtype=torch.cfloat)

    def x(self, qubit): pass
    def y(self, qubit): pass
    def z(self, qubit): pass
    def h(self, qubit): pass
    def Rx(self, qubit, angle): pass
    def Ry(self, qubit, angle): pass
    def Rz(self, qubit, angle): pass
    def R(self, qubit, theta, phi, lamda): pass
    def cx(self, control, target): pass
    def cz(self, control, target): pass
    def cx_linear_layer(self): pass
    def cz_linear_layer(self): pass
    def Ry_layer(self, angles): pass

# --- Basic Gate Inspection ---
print("## X, Y, Z gates")
num_qubits = 1
dim = 2 ** num_qubits
state_vector = torch.arange(1, dim + 1, dtype=torch.float32).to(torch.cfloat)
qc = quantum_circuit(num_qubits=num_qubits, state_vector=state_vector)

print(qc.state_vector, '= initial state vector\n')
print(qc.n, '= n')
print(qc.dim, '= dim\n')
print(qc.I, '= I')
print(qc.x_matrix, '= X')
print(qc.y_matrix, '= Y')
print(qc.z_matrix, '= Z')
print(qc.h_matrix, '= H')
print(qc.proj_0, '= proj_0')
print(qc.proj_1, '= proj_1\n')

qc.x(0)
print(qc.state_vector, '= final state vector\n')

# --- H gate example ---
print("## H gate")
num_qubits = 3
qc = quantum_circuit(num_qubits=num_qubits)
print(qc.state_vector, '= initial state vector\n')
qc.h(0)
qc.h(1)
print(qc.state_vector, '= final state vector\n')

# --- Rx, Ry, Rz gates ---
print("## Rx, Ry, Rz gates")
num_qubits = 2
qc = quantum_circuit(num_qubits=num_qubits)
print(qc.state_vector, '= initial state vector\n')

ang_ = torch.rand(1, requires_grad=True)
ang = ang_[0]
print([torch.cos(ang / 2), torch.sin(ang / 2)], '\n')
print([torch.cos(ang), torch.sin(ang)], '\n')
qc.Ry(0, ang)
print(qc.state_vector, '= final state vector\n')

# --- General R Gate ---
print("## General R gate")
num_qubits = 1
qc = quantum_circuit(num_qubits=num_qubits)
print(qc.state_vector, '= initial state vector\n')
ang_ = torch.rand(1, requires_grad=True)
ang = ang_[0]
zero = torch.tensor(0.0)
theta = zero
phi = zero
lamda = ang
qc.x(0)
qc.R(0, theta=theta, phi=phi, lamda=lamda)
print(qc.state_vector, '= final state vector\n')

# --- CX, CZ gates ---
print("## CX, CZ gates")
num_qubits = 3
state_vector = torch.arange(1, 2 ** num_qubits + 1, dtype=torch.float32).to(torch.cfloat)
qc = quantum_circuit(num_qubits=num_qubits, state_vector=state_vector)
print(qc.state_vector, '= initial state vector\n')
qc.cz(control=0, target=1)
print(qc.state_vector, '= final state vector\n')

# --- Multi Example State Vector ---
print("## Multi-sample input")
state_vector = torch.rand((2 ** 3, 2), dtype=torch.cfloat)
qc = quantum_circuit(num_qubits=3, state_vector=state_vector)
print(qc.state_vector, '= initial state vectors\n')
qc.cz(control=0, target=1)
print(qc.state_vector, '= final state vectors\n')

# --- CX Linear Layer Order Check ---
print("## CX Layer Order")
nn = 5
for i in range(nn - 3, -1, -1):
    print(i, i + 1)

# --- cx_linear_layer() ---
print("## cx_linear_layer")
state_vector = torch.arange(1, 2 ** 3 + 1, dtype=torch.float32).to(torch.cfloat)
qc = quantum_circuit(num_qubits=3, state_vector=state_vector)
print(qc.state_vector, '= initial state vector\n')
qc.cx_linear_layer()
print(qc.state_vector, '= final state vector\n')

# --- Ry_layer ---
print("## Ry_layer")
num_qubits = 2
qc = quantum_circuit(num_qubits=num_qubits)
print(qc.state_vector, '= initial state vector\n')
ang = torch.rand(num_qubits, dtype=torch.float32, requires_grad=True).to(torch.cfloat)
print('ang =', ang)
qc.Ry_layer(ang)


## X, Y, Z gates
tensor([1.+0.j, 2.+0.j]) = initial state vector

1 = n
2 = dim

tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]) = I
tensor([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]]) = X
tensor([[0.+0.j, -0.-1.j],
        [0.+1.j, 0.+0.j]]) = Y
tensor([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]) = Z
tensor([[ 0.7071+0.j,  0.7071+0.j],
        [ 0.7071+0.j, -0.7071+0.j]]) = H
tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]]) = proj_0
tensor([[0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]) = proj_1

tensor([1.+0.j, 2.+0.j]) = final state vector

## H gate
tensor([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]) = initial state vector

tensor([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]) = final state vector

## Rx, Ry, Rz gates
tensor([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]) = initial state vector

[tensor(0.9984, grad_fn=<CosBackward0>), tensor(0.0570, grad_fn=<SinBackward0>)] 

[tensor(0.9935, grad_fn=<CosBackward0>), tensor(0.1139, grad_fn=<Si

In [5]:
import torch
import math

def get_device(gpu_no=0):
    if torch.cuda.is_available():
        return torch.device(f'cuda:{gpu_no}')
    else:
        return torch.device('cpu')


class quantum_circuit:
    def __init__(self, num_qubits: int, state_vector=None, device='cuda', gpu_no=0):
        self.device = get_device(gpu_no) if device == 'cuda' else torch.device(device)
        self.n = num_qubits
        self.dim = 2 ** self.n

        if state_vector is None:
            state_vector = torch.zeros(self.dim, device=self.device, dtype=torch.cfloat)
            state_vector[0] = 1
            self.state_vector = state_vector.reshape(-1, 1)
        else:
            if state_vector.shape[0] == self.dim:
                self.state_vector = state_vector.to(self.device).to(torch.cfloat)
            else:
                raise ValueError('State vector shape does not match 2**n.')

        self.I = torch.eye(2, device=self.device, dtype=torch.cfloat)
        self.x_matrix = torch.tensor([[0, 1], [1, 0]], device=self.device, dtype=torch.cfloat)
        self.y_matrix = torch.tensor([[0, -1j], [1j, 0]], device=self.device, dtype=torch.cfloat)
        self.z_matrix = torch.tensor([[1, 0], [0, -1]], device=self.device, dtype=torch.cfloat)
        self.h_matrix = (1 / math.sqrt(2)) * torch.tensor([[1, 1], [1, -1]], device=self.device, dtype=torch.cfloat)
        self.proj_0 = torch.tensor([[1, 0], [0, 0]], device=self.device, dtype=torch.cfloat)
        self.proj_1 = torch.tensor([[0, 0], [0, 1]], device=self.device, dtype=torch.cfloat)

    def single_qubit_gate(self, target: int, gate: torch.Tensor):
        if not (0 <= target < self.n):
            raise ValueError('Target qubit index out of range.')
        gate_op = torch.tensor(1.0, device=self.device, dtype=torch.cfloat)
        for k in range(self.n):
            gate_op = torch.kron(gate_op, gate if k == target else self.I)
        self.state_vector = torch.matmul(gate_op, self.state_vector)
        return self.state_vector

    def controlled_gate(self, control: int, target: int, gate: torch.Tensor):
        if control == target:
            raise ValueError('Control and target must be different.')
        for idx in [control, target]:
            if not (0 <= idx < self.n):
                raise ValueError('Qubit index out of range.')

        gate_0 = torch.tensor(1.0, device=self.device, dtype=torch.cfloat)
        gate_1 = torch.tensor(1.0, device=self.device, dtype=torch.cfloat)

        for k in range(self.n):
            if k == control:
                gate_0 = torch.kron(gate_0, self.proj_0)
                gate_1 = torch.kron(gate_1, self.proj_1)
            elif k == target:
                gate_0 = torch.kron(gate_0, self.I)
                gate_1 = torch.kron(gate_1, gate)
            else:
                gate_0 = torch.kron(gate_0, self.I)
                gate_1 = torch.kron(gate_1, self.I)

        full_gate = gate_0 + gate_1
        self.state_vector = torch.matmul(full_gate, self.state_vector)
        return self.state_vector

    def x(self, target): self.single_qubit_gate(target, self.x_matrix)
    def y(self, target): self.single_qubit_gate(target, self.y_matrix)
    def z(self, target): self.single_qubit_gate(target, self.z_matrix)
    def h(self, target): self.single_qubit_gate(target, self.h_matrix)

    def Rx(self, target: int, theta):
        co = torch.cos(theta / 2)
        si = torch.sin(theta / 2)
        Rx_matrix = torch.stack([
            torch.stack([co, -1j * si]),
            torch.stack([-1j * si, co])
        ])
        self.single_qubit_gate(target, Rx_matrix)

    def Ry(self, target: int, theta):
        co = torch.cos(theta / 2)
        si = torch.sin(theta / 2)
        Ry_matrix = torch.stack([
            torch.stack([co, -si]),
            torch.stack([si, co])
        ])
        self.single_qubit_gate(target, Ry_matrix)

    def Rz(self, target: int, theta):
        exp_theta = torch.exp(1j * theta)
        Rz_matrix = torch.stack([
            torch.stack([torch.tensor(1.0, device=self.device), torch.tensor(0.0, device=self.device)]),
            torch.stack([torch.tensor(0.0, device=self.device), exp_theta])
        ])
        self.single_qubit_gate(target, Rz_matrix)

    def R(self, target: int, theta, phi, lamda):
        a = torch.cos(theta / 2)
        b = -torch.exp(1j * lamda) * torch.sin(theta / 2)
        c = torch.exp(1j * phi) * torch.sin(theta / 2)
        d = torch.exp(1j * (phi + lamda)) * torch.cos(theta / 2)
        R_matrix = torch.stack([torch.stack([a, b]), torch.stack([c, d])])
        self.single_qubit_gate(target, R_matrix)

    def Ry_layer(self, angs: torch.Tensor):
        rot = torch.stack([
            torch.stack([torch.cos(angs[0]), -torch.sin(angs[0])]),
            torch.stack([torch.sin(angs[0]),  torch.cos(angs[0])])
        ])
        for i in range(1, len(angs)):
            c, s = torch.cos(angs[i]), torch.sin(angs[i])
            single_rot = torch.stack([torch.stack([c, -s]), torch.stack([s, c])])
            rot = torch.kron(rot, single_rot)
        self.state_vector = torch.matmul(rot, self.state_vector)
        return self.state_vector

    def Rz_layer(self, angs: torch.Tensor):
        one = torch.tensor(1.0, device=self.device)
        zero = torch.tensor(0.0, device=self.device)
        rot = torch.stack([
            torch.stack([one, zero]),
            torch.stack([zero, torch.exp(1j * angs[0])])
        ])
        for i in range(1, len(angs)):
            e = torch.exp(1j * angs[i])
            single_rot = torch.stack([
                torch.stack([one, zero]),
                torch.stack([zero, e])
            ])
            rot = torch.kron(rot, single_rot)
        self.state_vector = torch.matmul(rot, self.state_vector)
        return self.state_vector

    def cx(self, control: int, target: int):
        self.controlled_gate(control, target, self.x_matrix)

    def cz(self, control: int, target: int):
        self.controlled_gate(control, target, self.z_matrix)

    def cx_linear_layer(self):
        self.cx(self.n - 2, self.n - 1)
        for i in range(self.n - 3, -1, -1):
            self.cx(i, i + 1)

    def cz_linear_layer(self):
        self.cz(self.n - 2, self.n - 1)
        for i in range(self.n - 3, -1, -1):
            self.cz(i, i + 1)

    def probabilities(self):
        return (self.state_vector.conj() * self.state_vector).real


In [6]:
qc = quantum_circuit(num_qubits=2)
qc.h(0)
qc.cx(0, 1)
print(qc.probabilities())


tensor([[0.5000],
        [0.0000],
        [0.0000],
        [0.5000]], device='cuda:0')
